server:
  port: 9090

spring:
  cloud:
    gateway:
      server: # New level added here
        webflux: # Specific for Reactive stack
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-api/v1/**

            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-api/v1/**

            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-api/v1/**
