spring:
  cloud:
    gateway:
      server: # New level added here
        webflux: # Specific for Reactive stack
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/orderServiceFallBack

            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCircuitBreaker
                    fallbackUri: forward:/fallback/paymentServiceFallBack

            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: productServiceCircuitBreaker
                    fallbackUri: forward:/fallback/productServiceFallBack
